=== fiprojects/walletcoach/data/xsd/subjects.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="subjects">
        <xs:complexType>
            <xs:choice>
                <xs:element name="subject" type="subject-type" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
        <xs:unique name="UniqueId">
            <xs:selector xpath="./subject" />
            <xs:field xpath="@id" />
        </xs:unique>
        
    </xs:element>
    
    <xs:complexType name="subject-type">
        <xs:all>
            <xs:element name="ic" type="xs:integer" minOccurs="1" />
            <xs:element name="name" type="xs:string" minOccurs="1" />
            <xs:element name="address" type="address-type" minOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="1" />
        </xs:all>
        <xs:attribute name="id" type="xs:integer" use="required" />
    </xs:complexType>
    
    <xs:complexType name="address-type">
        <xs:all>
            <xs:element name="street" type="xs:string" minOccurs="1" />
            <xs:element name="number" type="xs:string" minOccurs="1" />
            <xs:element name="city" type="xs:string" minOccurs="1" />
            <xs:element name="country" type="xs:string" minOccurs="1" />
        </xs:all>
    </xs:complexType>
</xs:schema>

=== fiprojects/walletcoach/data/subjects.xml
<subjects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/subjects.xsd">
  <subject id="1">
    <ic/>
    <name>Nezařazené</name>
    <address>
      <street/>
      <number/>
      <city/>
      <country/>
    </address>
    <description/>
  </subject>
</subjects>

=== fiprojects/walletcoach/etc/xml-structure/subjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<subjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="subjects.xsd"
>
  <subject id="1">
    <ic>36178429</ic>
    <name>Gazprom</name>
    <address>
      <street>Vasilevskaya ulica</street>
      <number>1/A</number>
      <city>Moskva</city>
      <country>Ruská federácia</country>
    </address>
    <description>Distribútor plynu</description>
  </subject>
</subjects>
