=== fiprojects/walletcoach/reports/yearReport.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="summary" type="valueType" />
                
                <xs:element name="categories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category">
                                <xs:complexType>
                                    <xs:sequence>
                                    </xs:sequence>

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="subjects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" type="valueType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
            <xs:attribute name="year" type="xs:integer" />
            <xs:attribute name="month" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="valueType">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="income" type="xs:positivedecimal" />
        <xs:attribute name="expense" type="xs:negativedecimal" />
        <xs:attribute name="total" type="xs:decimal" />
    </xs:complexType>
</xs:schema>

=== fiprojects/walletcoach/reports/xml/year_2015.xml
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" year="2015" xsi:noNamespaceSchemaLocation="xsd/yearReport.xsd">
  <summary>
    <income/>
    <expense>-100</expense>
    <total>-100</total>
  </summary>
  <categories>
    <category name="Nezařazené" income="0" expense="-100" total="-100"/>
  </categories>
  <subjects>
    <subject name="Nezařazené" income="0" expense="-100" total="-100"/>
  </subjects>
</report>
